### ISSUE TITLE
Emoji show as a Full Sized Images

### ISSUE THREAD

**Issue by ItzNotABug** [PrivacyVandaag/PrivacyVandaag#1]
Hey Hello!
I'used your project and its quite good but My feed posts has some emojis/smileys in them, my issue is that they appear as a Full sized Images and not small emojis...
SparseRss has this feature...
plz look into it.. 😊

**Comment by PrivacyVandaag** [comment]
Thank you for your comment. It is correct that the width of the images is set to 100%. It is supposed to do that.
If you want to change that, go to folder java/nl/privacybarometer/privacyvandaag/view and open the file EntryView.java. Near line 116 you will see: 
            + "img {height:auto;max-width:650px; width:100%; display:block; margin:0 auto 1em auto} "
Change in that line "width:100%" to "width:auto" and you are good to go.

**Comment by ItzNotABug** [comment]
Thanks for the Reply... :)
I'll just try & report back

**Comment by ItzNotABug** [comment]
Not able to Fetch any feed data from Wordpress Blogs...
Any Help?
the url I used is - https://lazygeniouz.wordpress.com/feed/
even the burned feed (via feedburner) of any this blog is not displaying any data...

**Comment by PrivacyVandaag** [comment]
I've added your url to the app and it reads the feed just fine. I replaced in FeedData java an existing url with your url like so: 
`FeedDataContentProvider.addFeed(context, "https://lazygeniouz.wordpress.com/feed/", "LazyGeniouz", true, "logo_icon_serviceberichten_inverse"); `
The app read your RSS feed correctly and consequently retrieved the full page from your website.
It looked fine to me. I noticed two other things though.
First, Most of the smileys used in your post are not images but unicode smileys, I guess? This will not display correctly on all android devices. Images will, but images in unicode will only show if available on the device.
Second, The extracting of the main body of your webpage to show in the app is not done properly. The app has a heuristic method to do this. This means it guesses the most likely part of your webpage to be the body or main article. On your page, it guesses almost right, but it retrieves a little bit to much. You can tweak this in Utils / ArticleTextExtractor.extractContent(); if you like. But if you are happy with the extracted content, then you can leave it as is of course.

**Comment by ItzNotABug** [comment]
As far as I know, they are Images & not unicodes...
and they still appear as Whole big pics even after setting the width to auto..
I tried Sparse Rss, it shows the Emojis perfectly without any tweaks...
